### ISSUE TITLE
Error when point process object includes events

### ISSUE THREAD

**Issue by OwenWard** [OwenWard/ppdiag#34]
When we do each of these, I think the warning messages should be consistent for both.
The warning message in the second case is more informative.
I think we can hide 
`longer object length is not a multiple of shorter object length`
in both cases though, and just say "using object"

`drawHPPIntensity(fit_hpp, events=hp_events$events, color = "red", fit=TRUE, plot_events=TRUE)`
`drawHPIntensity(fit_hp, events = hpp_events, plot_events = TRUE)`

@sallyqiansun we can discuss Tuesday. It's a small fix.
I think what we want is
- If there are events in the object and `events = NULL`, so not passed as an argument, use the object.
- If there are events in both, by default use those passed directly and have a message to that effect.

**Comment by sallyqiansun** [comment]
Just to double check, so if both events are provided in both argument and in object, we should prioritize the events in argument?

i.e. Is the logic like this?

if no events in object:
    if fit=True: 
        fit events in argument, plot fitted object parameters and events in argument
    if fit=False: 
        don't fit events in argument, plot object parameters and events in argument
if events is in object:
    if no events in argument:
        just plot object parameters and events in object
    if events is in argument:
        if fit=True:
            fit events in argument, plot fitted object parameters and events in argument
        if fit=False:
            don't fit events in argument, plot object parameters and events in argument

**Comment by OwenWard** [comment]
@sallyqiansun yes, I think that makes sense. once the documentation and messages are clear.

**Comment by OwenWard** [comment]
@sallyqiansun this hasn't been completed has it?
